#AndroidIDE: enforce UTF-8 & locale for Gradle daemon
#Mon Sep 21 04:47:50 GMT 2026
minSdkVersion=21
systemProp.user.language=en
systemProp.user.country=US
compileSdkVersion=36
ndkVersion=29.0.14206865
systemProp.sun.jnu.encoding=UTF-8
systemProp.file.encoding=UTF-8
markwonVersion=4.6.2
targetSdkVersion=28
org.gradle.jvmargs=-Xmx2048M -Dfile.encoding\=UTF-8 -Dsun.jnu.encoding\=UTF-8 -Duser.language\=en -Duser.country\=US
android.useAndroidX=true
